### ISSUE TITLE
ali-bookkeeping says "browser not supported" 

### ISSUE THREAD

**Issue by cholmcc** [AliceO2Group/Bookkeeping#808]
When visiting https://ali-bookkeeping.cern.ch from Android with Chrome 102 the page says browser not supported, but the supported browsers says Chrome 88.  Perhaps you are filtering on the OS too.   Surely Chrome 102 on Android should work too.  Thanks.

**Comment by graduta** [comment]
Hi @cholmcc 
Indeed, the message is not informative enough. We will look at adapting it.
I can confirm that mobile and table support is not yet on our deliverables plan. We will probably start looking at it in Q2 of 2023.
Thank you!
